# "service" is the name of this project. This will also be added to your AWS resource names.
service: anniyan-ai-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "lambda:InvokeFunction" # Permission to invoke other Lambdas
          Resource: "*"
  environment:
    OPEN_AI_API_KEY: ${env:OPEN_AI_API_KEY}
    OPEN_AI_ASSISTANT_ID: ${env:OPEN_AI_ASSISTANT_ID}

plugins:
  - serverless-offline

functions:
  application:
    handler: dist/serverlessHandler.api
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

